Document: coconet
Title: Debian coconet Manual
Author: <insert document author here>
Abstract: This manual describes what coconet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/coconet/coconet.sgml.gz

Format: postscript
Files: /usr/share/doc/coconet/coconet.ps.gz

Format: text
Files: /usr/share/doc/coconet/coconet.text.gz

Format: HTML
Index: /usr/share/doc/coconet/html/index.html
Files: /usr/share/doc/coconet/html/*.html

  
